### ISSUE TITLE
Interface zif_appl_object not included in repo

### ISSUE THREAD

**Issue by WegnerDan** [abapTools/abapHtmlButton#2]
The interface zif_appl_object is used in the following location, but is not in this repo.
https://github.com/abapTools/abapHtmlButton/blob/ff2b990ab7c8b09831b7c291fbc3db22636de19f/src/zif_html_button_cntl.intf.abap#L4

I tried to pull the current version and got activation errors. 
![image](https://user-images.githubusercontent.com/6908247/163282797-e06779fc-3938-4caf-8fcd-487f4036ad6d.png)

**Comment by preinboth** [comment]
Thanks for the tip. Will be fixed soon.
