### ISSUE TITLE
File zhtml_btn_pointer.tabl.xml and others exists 2 times in repository

### ISSUE THREAD

**Issue by chrisaasan** [abapTools/abapHtmlButton#4]
It looks like the generation of dotabap.org breaks because it detects this as a duplicate.

Check here: https://github.com/dotabap/dotabap-list/actions/runs/6143729310/job/16667753726

https://github.com/abapTools/abapHtmlButton/blob/main/src/zhtmlbutton_ddic/zhtml_btn_pointer.tabl.xml
https://github.com/abapTools/abapHtmlButton/blob/main/src/zhtml_btn_pointer.tabl.xml

**Comment by larshp** [comment]
thanks

**Comment by preinboth** [comment]
@chrisaasan , @larshp   I am at a loss to explain how this comes about. I also don't have a solution at hand. If this stops the generation of the list, the package can be removed from the list. I will take care of it later, if time permits.

**Comment by chrisaasan** [comment]
It looks like there has been some change in the package assignment for the DDIC objects, and that they now are defined 2 two times in the repository. Once in the root/src folder, and once in the zhtmlbutton_ddic folder.

**Comment by larshp** [comment]
yea, just remove one of the duplicate files

the cron is not critical, it can stay with errors for a few days

**Comment by preinboth** [comment]
File is deleted.

**Comment by larshp** [comment]
also check these files, 

```
Duplicate filename, abapTools/abapHtmlButton: zhtml_btn_pointer_tt.ttyp.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_btn_text.dtel.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_btn_type.dtel.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_btn_types.tabl.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_btn_types_tt.ttyp.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_button.tabl.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_button_fields.tabl.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_color_code.dtel.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_color_name.dtel.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_colors.tabl.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_colors_tt.ttyp.xml
Duplicate filename, abapTools/abapHtmlButton: zhtml_guid.dtel.xml
```

**Comment by preinboth** [comment]
Repository deleted from the list. When it is ready to run again, it will be back in the list.
